name: nmr
channels:
  - conda-forge
  - defaults
dependencies:
  - asn1crypto=0.24.0=py37_0
  - atomicwrites=1.3.0=py37_1
  - attrs=19.1.0=py_0
  - backcall=0.1.0=py_0
  - blas=1.0=mkl
  - bleach=3.1.0=py_0
  - ca-certificates=2019.5.15=0
  - certifi=2019.6.16=py37_0
  - cffi=1.12.2=py37h7a1dbc1_1
  - chardet=3.0.4=py37_1
  - colorama=0.4.1=py_0
  - coverage=4.5.3=py37he774522_0
  - cryptography=2.6.1=py37h7a1dbc1_0
  - cycler=0.10.0=py37_0
  - cython=0.29.6=py37ha925a31_0
  - decorator=4.4.0=py_0
  - defusedxml=0.5.0=py_1
  - entrypoints=0.3=py37_1000
  - freetype=2.9.1=ha9979f8_1
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha66f8fd_1
  - idna=2.8=py37_0
  - intel-openmp=2019.3=203
  - ipykernel=5.1.0=py37h39e3cac_0
  - ipython=7.4.0=py37h39e3cac_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.4.2=py37_0
  - jedi=0.13.3=py37_0
  - jinja2=2.10=py_1
  - jpeg=9b=hb83a4c4_2
  - jsonschema=3.0.1=py37_0
  - jupyter=1.0.0=py37_7
  - jupyter_client=5.2.4=py_3
  - jupyter_console=6.0.0=py37_0
  - jupyter_core=4.4.0=py_0
  - jupyterlab=0.35.4=py37_0
  - jupyterlab_server=0.2.0=py_0
  - kiwisolver=1.0.1=py37h6538335_0
  - libpng=1.6.36=h2a8f88b_0
  - libsodium=1.0.16=h2fa13f4_1001
  - libtiff=4.0.10=hb898794_2
  - line_profiler=2.1.2=py37hfa6e2cd_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=1.1.1=py37hfa6e2cd_0
  - matplotlib=3.0.3=py37hc8f65d3_0
  - memory_profiler=0.55.0=py37_0
  - mistune=0.8.4=py37hfa6e2cd_1000
  - mkl=2019.3=203
  - mkl_fft=1.0.10=py37h14836fe_0
  - mkl_random=1.0.2=py37h343c172_0
  - more-itertools=6.0.0=py37_0
  - msys2-conda-epoch=20160418=1
  - nb_conda_kernels=2.2.0=py37_1
  - nbconvert=5.4.1=py_2
  - nbformat=4.4.0=py_1
  - notebook=5.7.7=py37_0
  - numpy=1.16.2=py37h19fb1c0_0
  - numpy-base=1.16.2=py37hc3f5095_0
  - olefile=0.46=py37_0
  - openssl=1.1.1c=he774522_1
  - pandoc=2.7.1=0
  - pandocfilters=1.4.2=py_1
  - parso=0.3.4=py_0
  - pickleshare=0.7.5=py37_1000
  - pillow=6.0.0=py37hdc69c19_0
  - pip=19.0.3=py37_0
  - plotly=3.7.0=py_0
  - pluggy=0.9.0=py37_0
  - prometheus_client=0.6.0=py_0
  - prompt_toolkit=2.0.9=py_0
  - psutil=5.6.2=py37he774522_0
  - py=1.8.0=py37_0
  - pycparser=2.19=py37_0
  - pygments=2.3.1=py_0
  - pympler=0.7=py_0
  - pyopenssl=19.0.0=py37_0
  - pyparsing=2.4.0=py_0
  - pyqt=5.9.2=py37h6538335_2
  - pyrsistent=0.14.11=py37hfa6e2cd_0
  - pysocks=1.6.8=py37_0
  - pytest=4.4.0=py37_1
  - python=3.7.3=h8c8aaf0_0
  - python-dateutil=2.8.0=py_0
  - pytz=2019.1=py_0
  - pywinpty=0.5.5=py37_1000
  - pyzmq=18.0.1=py37he418aac_0
  - qt=5.9.7=vc14h73c81de_0
  - qtconsole=4.4.3=py37_0
  - requests=2.21.0=py37_0
  - retrying=1.3.3=py37_2
  - scipy=1.2.1=py37h29ff71c_0
  - send2trash=1.5.0=py37_0
  - setuptools=40.8.0=py37_0
  - sip=4.19.8=py37h6538335_0
  - six=1.12.0=py37_1000
  - snakeviz=1.0.0=py37_0
  - sqlite=3.27.2=he774522_0
  - terminado=0.8.2=py37_0
  - testpath=0.4.2=py_1001
  - tk=8.6.8=hfa6e2cd_0
  - tornado=6.0.2=py37hfa6e2cd_0
  - traitlets=4.3.2=py37_1000
  - urllib3=1.24.1=py37_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.15.26706=h3a45250_0
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - wheel=0.33.1=py37_0
  - widgetsnbextension=3.4.2=py37_0
  - win_inet_pton=1.1.0=py37_0
  - wincertstore=0.2=py37_0
  - winpty=0.4.3=4
  - xz=5.2.4=h2fa13f4_4
  - zeromq=4.2.5=he025d50_1006
  - zlib=1.2.11=h62dcd97_3
  - zstd=1.3.7=h508b16e_0
  - pip:
    - llvmlite==0.28.0
    - numba==0.43.1
    - pyfakefs==3.5.8
    - sparse==0.7.0
prefix: C:\Users\Geoffrey\Miniconda3\envs\nmr

