name: qm
channels:
  - conda-forge
  - anaconda-fusion
  - defaults
dependencies:
#  - ca-certificates=2018.4.16
#  - certifi=2018.4.16
#  - ipywidgets=7.2.1
#  - jupyterlab=0.33.6
#  - jupyterlab_launcher=0.11.2
#  - openssl=1.0.2o
#  - qutip=4.3.1
  - widgetsnbextension=3.2.1
#  - _nb_ext_conf=0.4.0
#  - alabaster=0.7.11
#  - anaconda-client=1.6.14
#  - appdirs=1.4.3
#  - appnope=0.1.0
#  - asn1crypto=0.24.0
#  - astroid=1.6.5
#  - atomicwrites=1.1.5
#  - attrs=18.1.0
#  - automat=0.7.0
#  - babel=2.6.0
#  - backcall=0.1.0
#  - blas=1.0
#  - bleach=2.1.3
  - bokeh=0.13.0
#  - cffi=1.11.5
#  - chardet=3.0.4
#  - cloudpickle=0.5.3
#  - clyent=1.2.2
#  - constantly=15.1.0
#  - cryptography=2.2.2
#  - cycler=0.10.0
#  - cython=0.28.4
#  - dbus=1.13.2
#  - decorator=4.3.0
#  - docutils=0.14
#  - entrypoints=0.2.3
#  - expat=2.2.5
#  - fastcache=1.0.2
#  - freetype=2.9.1
#  - gettext=0.19.8.1
#  - glib=2.56.1
#  - gmp=6.1.2
#  - gmpy2=2.0.8
#  - holoviews=1.10.7
#  - html5lib=1.0.1
#  - hyperlink=18.0.0
#  - icu=58.2
#  - idna=2.7
#  - imagesize=1.0.0
#  - incremental=17.5.0
#  - intel-openmp=2018.0.3
#  - ipykernel=4.8.2
#  - ipython=6.4.0
#  - ipython_genutils=0.2.0
#  - isort=4.3.4
#  - jedi=0.12.1
#  - jinja2=2.10
#  - jpeg=9b
#  - jsonschema=2.6.0
#  - jupyter=1.0.0
#  - jupyter_client=5.2.3
#  - jupyter_console=5.2.0
#  - jupyter_core=4.4.0
#  - keyring=13.2.1
#  - kiwisolver=1.0.1
#  - lazy-object-proxy=1.3.1
#  - libcxx=4.0.1
#  - libcxxabi=4.0.1
#  - libedit=3.1.20170329
#  - libffi=3.2.1
#  - libgfortran=3.0.1
#  - libiconv=1.15
#  - libopenblas=0.2.20
#  - libpng=1.6.34
#  - libsodium=1.0.16
#  - markupsafe=1.0
  - matplotlib=2.2.2
#  - mccabe=0.6.1
#  - mistune=0.8.3
#  - mkl=2018.0.3
#  - mkl_fft=1.0.4
#  - mkl_random=1.0.1
#  - more-itertools=4.2.0
#  - mpc=1.1.0
#  - mpfr=4.0.1
#  - mpmath=1.0.0
#  - nb_anacondacloud=1.4.0
#  - nb_conda=2.2.1
#  - nb_conda_kernels=2.1.0
#  - nbconvert=5.3.1
#  - nbformat=4.4.0
#  - nbpresent=3.0.2
#  - ncurses=6.1
#  - nose=1.3.7
#  - notebook=5.6.0
  - numpy=1.15.0
#  - numpy-base=1.15.0
#  - numpydoc=0.8.0
#  - packaging=17.1
#  - pandoc=2.2.1
#  - pandocfilters=1.4.2
#  - param=1.7.0
#  - parso=0.3.1
#  - pcre=8.42
#  - pexpect=4.6.0
#  - pickleshare=0.7.4
#  - pip=10.0.1
  - plotly=3.1.0
#  - pluggy=0.6.0
#  - prometheus_client=0.3.0
#  - prompt_toolkit=1.0.15
#  - psutil=5.4.6
#  - ptyprocess=0.6.0
#  - py=1.5.4
#  - pyasn1=0.4.3
#  - pyasn1-modules=0.2.2
#  - pycodestyle=2.4.0
#  - pycparser=2.18
#  - pyflakes=2.0.0
#  - pygments=2.2.0
#  - pylint=1.9.2
#  - pyopenssl=18.0.0
#  - pyparsing=2.2.0
#  - pyqt=5.9.2
#  - pysocks=1.6.8
#  - pytest=3.6.3
  - python=3.6
#  - python-dateutil=2.7.3
#  - python.app=2
#  - pytz=2018.5
#  - pyviz_comms=0.1.1
#  - pyyaml=3.13
#  - pyzmq=17.0.0
#  - qt=5.9.6
#  - qtawesome=0.4.4
#  - qtconsole=4.3.1
#  - qtpy=1.4.2
#  - qutip=*
#  - readline=7.0
#  - requests=2.19.1
#  - retrying=1.3.3
#  - rope=0.10.7
#  - scipy=1.1.0
#  - send2trash=1.5.0
#  - service_identity=17.0.0
#  - setuptools=39.2.0
#  - simplegeneric=0.8.1
#  - sip=4.19.8
#  - six=1.11.0
#  - snowballstemmer=1.2.1
  - sparse
#  - sphinx=1.7.6
#  - sphinxcontrib=1.0
#  - sphinxcontrib-websupport=1.1.0
#  - spyder=3.3.0
#  - spyder-kernels=0.2.4
#  - sqlite=3.24.0
#  - sympy=1.2
#  - terminado=0.8.1
#  - testpath=0.3.1
#  - tk=8.6.7
#  - tornado=5.0.2
#  - traitlets=4.3.2
#  - twisted=17.5.0
#  - urllib3=1.23
#  - wcwidth=0.1.7
#  - webencodings=0.5.1
#  - wheel=0.31.1
#  - wrapt=1.10.11
#  - xz=5.2.4
#  - yaml=0.1.7
#  - zeromq=4.2.5
#  - zlib=1.2.11
#  - zope=1.0
#  - zope.interface=4.5.0
  - pip:
#    - nmrglue==0.6
#    - sphinx-rtd-theme==0.4.0
prefix: /Users/geoffreysametz/anaconda/envs/qm

