name: Publish to PyPI

on:
  create:
    tags:
      - '*'

jobs:
  call_codequality:
    uses: ./.github/workflows/codequality.yml

  build_source_dist:
    name: Build source distribution
    needs: call_codequality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install build
        run: python -m pip install build

      - name: Run build
        run: python -m build --sdist --wheel

      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

#  build_wheels:
#    name: Build wheels on ${{ matrix.os }}
#    needs: build_source_dist
#    runs-on: ${{ matrix.os }}
#    strategy:
#      matrix:
#        os: [ubuntu-20.04, windows-2019, macOS-10.15]
#
#    steps:
#      - uses: actions/checkout@v3
#
#      - uses: actions/setup-python@v4
#        with:
#          python-version: "3.10"
#
#      - name: Install cibuildwheel
#        run: python -m pip install cibuildwheel==2.3.1
#
#      - name: Build wheels
#        run: python -m cibuildwheel --output-dir wheels
#
#      - uses: actions/upload-artifact@v3
#        with:
#          path: ./wheels/*.whl

  publish:
    name: Publish package to PyPI
#    if: startsWith(github.event.ref, 'refs/tags/v')
    needs:
      - build_source_dist
#      - build_wheels
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist  # unmangle to `./dist` to actually publish

      - uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
